"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Header from './component/header'
import Footer from './component/footer'
import 'bootstrap/dist/css/bootstrap.min.css';
import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap-css-only/css/bootstrap.min.css";
import "mdbreact/dist/css/mdb.css";
import { usePathname, useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentPage = usePathname();
  const router = useRouter();
  
  return (
    <html lang="en">
      <body>
        {currentPage == '/login' || currentPage == '/register' ? '' : <Header />}
          {children}
        {currentPage == '/login' || currentPage == '/register' ? '' : <Footer />}
      </body>
    </html>
  )
}
